export const vehicles = [
  {
    "id": 1,
    "name": "Model S",
    "brand": "Tesla",
    "model": "Long Range",
    "year": "2023",
    "version": "Luxury",
    "traction": "AWD",
    "motor": "Electric",
    "fuel": "Electric",
    "transmission": "Automatic",
    "kilometers": "15000",
    "armor": "0",
    "price": "75000",
    "image": "tesla_model_s.jpg",
    "description": "A premium electric sedan with advanced features",
    "owner": "OWN001"
  },
  {
    "id": 2,
    "name": "Civic",
    "brand": "Honda",
    "model": "EX",
    "year": "2021",
    "version": "Sedan",
    "traction": "FWD",
    "motor": "2.0L I4",
    "fuel": "Gasoline",
    "transmission": "CVT",
    "kilometers": "25000",
    "armor": "0",
    "price": "22000",
    "image": "honda_civic_ex.jpg",
    "description": "Reliable and fuel-efficient compact sedan",
    "owner": "OWN002"
  },
  {
    "id": 3,
    "name": "F-150",
    "brand": "Ford",
    "model": "XLT",
    "year": "2022",
    "version": "Truck",
    "traction": "4WD",
    "motor": "3.5L V6",
    "fuel": "Gasoline",
    "transmission": "Automatic",
    "kilometers": "18000",
    "armor": "Yes",
    "price": "45000",
    "image": "ford_f150_xlt.jpg",
    "description": "A powerful truck suitable for off-road and heavy-duty tasks",
    "owner": "OWN003"
  },
  {
    "id": 4,
    "name": "Corolla",
    "brand": "Toyota",
    "model": "LE",
    "year": "2020",
    "version": "Sedan",
    "traction": "FWD",
    "motor": "1.8L I4",
    "fuel": "Gasoline",
    "transmission": "Automatic",
    "kilometers": "30000",
    "armor": "0",
    "price": "19000",
    "image": "toyota_corolla_le.jpg",
    "description": "A compact and fuel-efficient sedan with advanced safety features",
    "owner": "OWN001"
  },
  {
    "id": 5,
    "name": "Wrangler",
    "brand": "Jeep",
    "model": "Rubicon",
    "year": "2023",
    "version": "SUV",
    "traction": "4WD",
    "motor": "3.6L V6",
    "fuel": "Gasoline",
    "transmission": "Manual",
    "kilometers": "5000",
    "armor": "Yes",
    "price": "52000",
    "image": "jeep_wrangler_rubicon.jpg",
    "description": "A rugged off-road SUV perfect for adventures",
    "owner": "OWN002"
  },
  {
    "id": 6,
    "name": "Mustang",
    "brand": "Ford",
    "model": "GT",
    "year": "2022",
    "version": "Coupe",
    "traction": "RWD",
    "motor": "5.0L V8",
    "fuel": "Gasoline",
    "transmission": "Manual",
    "kilometers": "12000",
    "armor": "0",
    "price": "55000",
    "image": "ford_mustang_gt.jpg",
    "description": "A classic American muscle car with a powerful V8 engine",
    "owner": "OWN003"
  },
  {
    "id": 7,
    "name": "Model X",
    "brand": "Tesla",
    "model": "Plaid",
    "year": "2023",
    "version": "Luxury SUV",
    "traction": "AWD",
    "motor": "Electric",
    "fuel": "Electric",
    "transmission": "Automatic",
    "kilometers": "8000",
    "armor": "0",
    "price": "99000",
    "image": "tesla_model_x_plaid.jpg",
    "description": "A high-performance electric SUV with falcon-wing doors",
    "owner": "OWN001"
  },
  {
    "id": 8,
    "name": "Camry",
    "brand": "Toyota",
    "model": "XSE",
    "year": "2021",
    "version": "Sedan",
    "traction": "FWD",
    "motor": "2.5L I4",
    "fuel": "Gasoline",
    "transmission": "Automatic",
    "kilometers": "22000",
    "armor": "0",
    "price": "28000",
    "image": "toyota_camry_xse.jpg",
    "description": "A sporty and comfortable mid-size sedan",
    "owner": "OWN002"
  },
  {
    "id": 9,
    "name": "Ranger",
    "brand": "Ford",
    "model": "Lariat",
    "year": "2022",
    "version": "Truck",
    "traction": "4WD",
    "motor": "2.3L I4 Turbo",
    "fuel": "Gasoline",
    "transmission": "Automatic",
    "kilometers": "17000",
    "armor": "0",
    "price": "42000",
    "image": "ford_ranger_lariat.jpg",
    "description": "A mid-size truck with great towing capability",
    "owner": "OWN003"
  },
  {
    "id": 10,
    "name": "Accord",
    "brand": "Honda",
    "model": "Touring",
    "year": "2023",
    "version": "Sedan",
    "traction": "FWD",
    "motor": "2.0L Turbo",
    "fuel": "Gasoline",
    "transmission": "Automatic",
    "kilometers": "11000",
    "armor": "0",
    "price": "35000",
    "image": "honda_accord_touring.jpg",
    "description": "A stylish and spacious sedan with premium features",
    "owner": "OWN001"
  }
];
